//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fendahl_Frm_Training_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION
    {
        public REGISTRATION()
        {
            this.FEEDBACK = new HashSet<FEEDBACK>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int AGE { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<FEEDBACK> FEEDBACK { get; set; }
    }
}
