//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fendahl_Frm_Training_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FENDAHL_EXAMINATION_Context : DbContext
    {
        public FENDAHL_EXAMINATION_Context()
            : base("name=FENDAHL_EXAMINATION_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FEEDBACK> FEEDBACK { get; set; }
        public DbSet<REGISTRATION> REGISTRATION { get; set; }
    }
}
